font_family      FiraCode Nerd Font Mono
font_size        16.0
disable_ligatures      always

dynamic_background_opacity yes
background_opacity 0.7
background_blur 0

window_padding_width 4

cursor none
cursor_blink_interval 0

# mouse
url_prefixes file ftp ftps git http https mailto sftp ssh
strip_trailing_spaces always
select_by_word_characters @-./_~?&=%+#

# windows layout
remember_window_size  no
initial_window_width  1280
initial_window_height 720
enabled_layouts splits, stack

# tab bar
tab_bar_style powerline
tab_powerline_style round

macos_quit_when_last_window_closed yes

allow_remote_control yes
listen_on unix:/tmp/kitty

map ctrl+alt+v launch --loc=vsplit
map ctrl+alt+b launch --loc=hsplit

map ctrl+alt+l neighboring_window right
map ctrl+alt+h neighboring_window left
map ctrl+alt+k neighboring_window up
map ctrl+alt+j neighboring_window down
map ctrl+alt+p neighboring_window previous

map ctrl+alt+right kitten @ resize-window --axis horizontal --increment 10 --self
map ctrl+alt+left  kitten @ resize-window --axis horizontal --increment -10 --self
map ctrl+alt+up    kitten @ resize-window --axis vertical --increment 10 --self
map ctrl+alt+down  kitten @ resize-window --axis vertical --increment -10 --self

map ctrl+shift+t new_tab
map ctrl+shift+tab previous_tab
map ctrl+tab next_tab
