import = [
    "~/.config/alacritty/themes/themes/gruvbox_light.toml"
]
live_config_reload = false

[shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 15 }
dynamic_padding = false


[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }
size = 13.0

