alias ls="ls -F --color=auto --group-directories-first"
alias ll="ls -lh --time-style=long-iso"
alias la="ls -A"

alias gs="git status -s 2>/dev/null"
alias gck="git checkout"
alias gcp="git cherry-pick"
alias ga="git add"
alias gd="git diff"
alias gc="git commit"
alias gb="git branch"
alias gds="git diff --staged"
alias gdw="git diff --word-diff"
alias gdws="git diff --word-diff --staged"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset%C(yellow)%d%Creset %s%Cgreen(%cr)' --abbrev-commit"
alias gcl="git clone"

alias ipython="python3 -m IPython"

alias wopen="/mnt/c/Windows/explorer.exe"
alias vi="nvim"
alias ssh="TERM=xterm-256color /usr/bin/ssh"
