case $- in 
    *i*) ;;
    *) return;;
esac

ZDOTDIR="$HOME/.config/zsh"
ZSHAREDIR="$HOME/.local/share/zsh"

HISTFILE="$ZSHAREDIR/history"
fpath=($fpath $ZSHAREDIR/site-functions/)

[[ $OSTYPE == "Darwin"* ]] && source "$HOME/.config/zsh/mac.zsh"

setopt AUTO_CD
setopt INTERACTIVE_COMMENTS
setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_ALL_DUPS
setopt SHARE_HISTORY

unsetopt AUTO_REMOVE_SLASH
unsetopt HIST_EXPIRE_DUPS_FIRST
unsetopt EXTENDED_HISTORY

[[ ! -f "$ZSHAREDIR/installed" ]] && \
    "$HOME/.config/zsh/install.zsh" && \
    touch "$ZSHAREDIR/installed"


CONDA_FORGE_DEFAULT_DIR="$HOME/.local/miniforge"
CONDA_FORGE_DIR="${CONDA_FORGE_DIR:-$CONDA_FORGE_DEFAULT_DIR}"
function condainit() {
    eval "$($CONDA_FORGE_DIR/bin/conda shell.zsh hook)"
}

autoload -Uz compinit
for lib in $ZSHAREDIR/lib/*.zsh; do
    source $lib 
done

SHARE_DEFAULT_DIR="/usr/share"
SHARE_DIR="${SHARE_DIR:-$SHARE_DEFAULT_DIR}"
for p in "$SHARE_DIR"/zsh-*(N); do 
    source $p/$(basename $p).zsh; 
done
unset SHARE_DEFAULT_DIR SHARE_DIR CONDA_FORGE_DEFAULT_DIR

zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select
zstyle ":completion:*" use-cache yes
zstyle ":completion:*" squeeze-slashes true
zstyle ":completion:*" file-sort change
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' cache-path $ZSHAREDIR/zcompdumpcache
compinit -d $ZSHAREDIR/zcompdump

source $ZSHAREDIR/theme/p10k/powerlevel10k.zsh-theme
[[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]] && \
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
[[ ! -f $HOME/.p10k.zsh ]] || source $HOME/.p10k.zsh

if command -v fzf >/dev/null 2>&1; then
    FIND_CMD=$(command -v fd || command -v fdfind || echo find)
    export FZF_DEFAULT_OPTS="--height=10 --layout=reverse"
    export FZF_DEFAULT_COMMAND="${FIND_CMD} --type f --strip-cwd-prefix --follow --exclude=.venv,.config,.git,.local"
    unset FIND_CMD
    eval "$(fzf --zsh)"
fi

command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init zsh)"

unset ZSHAREDIR ZDOTDIR

source $HOME/.config/zsh/alias.sh
