syntax on
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on

set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4

set noerrorbells
set novisualbell

let mapleader = " "
inoremap <silent> jk <esc>
nnoremap <silent> H <s-up>
nnoremap <silent> L <s-down>
nnoremap <silent> <leader>v <c-v>
nnoremap <silent> n nzz
nnoremap <silent> N Nzz
nnoremap <silent> S :w<Return>
nnoremap <silent> Q :q<Return>
nnoremap <silent> ss :split<Return><C-w>w
nnoremap <silent> sv :vsplit<Return><C-w>w
nnoremap <silent> <Space> <C-w>w
nnoremap <silent> sq <C-w>q
nnoremap <silent> sh <C-w>h
nnoremap <silent> sk <C-w>k
nnoremap <silent> sj <C-w>j
nnoremap <silent> sl <C-w>l
nnoremap <silent> s<left> <C-w>5<
nnoremap <silent> s<right> <C-w>5>
nnoremap <silent> s<up> <C-w>5+
nnoremap <silent> s<down> <C-w>-
