#!/bin/bash

if command -v paru >/dev/null 2>&1; then
    return 0
fi

sudo pacman -S --needed base-devel
temp_path=$(mktemp -d)
trap 'rm -rf "$temp_path"' EXIT
git clone https://aur.archlinux.org/paru.git $temp_path
cd $temp_path
makepkg -si
cd -

