#!/bin/bash

set -e

if [[ $(uname -s) == "Darwin" ]]; then
  brew update
else
  sudo apt update
  sudo apt install -y zsh
fi
file_path="$(dirname "$(realpath "$0")")"

export file_path
exec $file_path/proxy
