#!/bin/zsh
set -e

os_type=$(uname -s);

if [[ $os_type == "Darwin" ]]; then
  alias pkg_install="brew install --quiet -y";
  pkg_index=1;
elif [[ $os_type == "Linux" ]]; then
  alias pkg_install="sudo apt install -y";
  pkg_index=2;
fi
echo "Running init script for $os_type...";

data_path="$HOME/.local/share";
cfg_path="$HOME/.config";

pkgs=(
  wget
  curl
  mpv
  ffmpeg
  jq
  fzf
  ripgrep
  xclip
  htop
  zoxide
  eza
  unzip
  zip
  tmux
  zsh-autosuggestions
  cmake
  gradle
)


groups=(
  "fd:fd-find"
  "yazi:"
  "rustup:"
  "openjdk:openjdk"
  "sevenzip:7zip"
  "poppler:poppler-utils"
  ":clang"
  ":lldb"
  ":gdb"
  ":kitty"
  "neovim:"
)


for g in "${groups[@]}"; do
  parts=("${(@s.:.)g}")
  [[ -n $parts[$pkg_index] ]] && pkgs+=($parts[$pkg_index])
done
pkg_install "${pkgs[@]}"
unset pkgs groups parts g
unalias pkg_install 

for file in "$file_path"/*.sh; do
    if [ -f "$file" ]; then
        echo "Running $file..."
        . "$file"
    fi
done

ossp_path=$file_path/$os_type
echo "Running $ossp_path/init..."
[ -f $ossp_path/init ] && . $ossp_path/init

for file in "$ossp_path"/*.sh; do
    if [ -f "$file" ]; then
        echo "Running $file..."
        . "$file"
    fi
done
unset file_path ossp_path

unset data_path cfg_path os_type
