HISTFILE="$HOME/.local/share/zsh/history"

export EDITOR="nvim"

# go
export GO111MODULE=on
export GOPROXY=https://goproxy.cn
export GOPATH=$HOME/.local/gohome

# fzf
FIND_CMD=find
if command -v fd &>/dev/null; then
    FIND_CMD=fd
elif command -v fdfind &>/dev/null; then
    FIND_CMD=fdfind
fi
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border"
export FZF_DEFAULT_COMMAND="${FIND_CMD} --type f --strip-cwd-prefix --follow --exclude=.venv,.config,.git,.local"
unset FIND_CMD
