case $- in
  *i*) ;;
  *) return;;
esac

ZDOTDIR="$HOME/.config/zsh"
ZSHAREDIR="$HOME/.local/share/zsh"

HISTFILE="$ZSHAREDIR/history"

setopt AUTO_CD
setopt INTERACTIVE_COMMENTS
setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_ALL_DUPS
setopt SHARE_HISTORY

unsetopt AUTO_REMOVE_SLASH
unsetopt HIST_EXPIRE_DUPS_FIRST
unsetopt EXTENDED_HISTORY

autoload -Uz compinit
for lib in $ZSHAREDIR/lib/*.zsh; do
  source $lib
done

zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select
zstyle ":completion:*" use-cache yes
zstyle ":completion:*" squeeze-slashes true
zstyle ":completion:*" file-sort change
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' cache-path $ZSHAREDIR/zcompdumpcache
compinit -d $ZSHAREDIR/zcompdump

source $HOME/.local/share/zsh/zsh-powerlevel10k/powerlevel10k.zsh-theme
source $HOME/.local/share/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
[[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]] && \
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
[[ ! -f $HOME/.p10k.zsh ]] || source $HOME/.p10k.zsh

source $ZDOTDIR/alias.sh
source $ZDOTDIR/tools.sh

unset ZSHAREDIR ZDOTDIR

