case $- in
  *i*) ;;
  *) return;;
esac

ZDOTDIR="$HOME/.config/zsh"
ZSHAREDIR="$HOME/.local/share/zsh"

HISTFILE="$ZSHAREDIR/history"

setopt AUTO_CD
setopt INTERACTIVE_COMMENTS
setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_ALL_DUPS
setopt SHARE_HISTORY

unsetopt AUTO_REMOVE_SLASH
unsetopt HIST_EXPIRE_DUPS_FIRST
unsetopt EXTENDED_HISTORY

autoload -Uz compinit
source $ZSHAREDIR/oh-my-zsh/lib/clipboard.zsh
source $ZSHAREDIR/oh-my-zsh/lib/git.zsh
source $ZSHAREDIR/oh-my-zsh/lib/history.zsh
source $ZSHAREDIR/oh-my-zsh/lib/key-bindings.zsh
source $ZSHAREDIR/oh-my-zsh/lib/theme-and-appearance.zsh
source $ZSHAREDIR/oh-my-zsh/lib/async_prompt.zsh

zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select
zstyle ":completion:*" use-cache yes
zstyle ":completion:*" squeeze-slashes true
zstyle ":completion:*" file-sort change
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' cache-path $ZSHAREDIR/zcompdumpcache
compinit -d $ZSHAREDIR/zcompdump

source $ZSHAREDIR/zsh-autosuggestions/zsh-autosuggestions.zsh

source $ZDOTDIR/theme.sh
source $ZDOTDIR/alias.sh
source $ZDOTDIR/tools.sh

unset ZSHAREDIR ZDOTDIR

